
function getytdatamr(){
    var geturl = document.querySelector("#youtubevideolink").value;
    var urlsplit= geturl.split(/^.*(youtu.be\/|v\/|embed\/|watch\?|youtube.com\/user\/[^#]*#([^\/]*?\/)*)\??v?=?([^#\&\?]*).*/);
    var videoIdmr = urlsplit[3];	

    vMRchannelId = "UC8uhhaqA9s540gufCwKwrKA";
    var mrApi = "AIzaSyDSwN5XQQfJvYhY4iLMf3DZmUr6MdCjawg";
    var videoData1 = "https://www.googleapis.com/youtube/v3/videos?part=statistics&id="+videoIdmr+"&key="+mrApi+"";
    var videoData2 = "https://www.googleapis.com/youtube/v3/videos?part=id%2C+snippet&id="+videoIdmr+"&key="+mrApi+"";
    var videofrmSRC = "https://www.youtube.com/embed/"+videoIdmr+"?rel=0&autoplay=1";
    var videoMRThumbnail = "https://i.ytimg.com/vi/"+videoIdmr+"/maxresdefault.jpg";
    $.ajax({
    type: "GET",
    dataType: "json",
    url: videoData2,
    success: function(data2) {
    var vt = data2.items[0].snippet.title;
    var vs = data2.items[0].snippet.description;
    var vdate = data2.items[0].snippet.publishedAt;
$('#output').val(schema(vt,vs,videoIdmr,vdate))
$('#youtubevideotitle').val(vt)

    }
    });

        };

function schema(a,b,c,d){
return '<iframe class="lazyload" title="'+a+'" width="100%" height="400px" allowfullscreen allow="accelerometer;autoplay;encrypted-media;gyroscope;picture-in-picture" data-style="background: url(https://img.youtube.com/vi/'+c+'/hqdefault.jpg) 50% 50% / cover no-repeat;" data-src="https://www.youtube.com/embed/'+c+'"></iframe><img class="dnone" src="https://i.ytimg.com/vi/'+c+'/maxresdefault.jpg" alt="'+a+'" title="'+a+'"><script type="application/ld+json">{"@context": "http://schema.org","@type": "VideoObject","name": "'+a+'","description": "'+b+'","thumbnailUrl": "https://i.ytimg.com/vi/'+c+'/maxresdefault.jpg","uploadDate": "'+d+'","duration": "PT4M43S","embedUrl": "https://www.youtube.com/embed/'+c+'","interactionCount": "2985"}</script><!--Video Markup Code Generated by https://www.neotericit.com/ --><h2>'+a+'</h2><p>'+b+'</p>'
}


 function copyallcode(){
  navigator.clipboard.writeText($('#output').val());
 $('.copyallcode').text('copied')
 }
   function copytitle(){
  navigator.clipboard.writeText($('#youtubevideotitle').val());
 $('.copytitle').text('copied')
 }
